name = "larp-bot-telegram-egress"
main = "src/index.ts"
compatibility_date = "2026-08-20"
workers_dev = true

[secrets]
required = [
  "TG_BOT_TOKEN",
  "YANDEX_TO_CF_EGRESS_HMAC_SECRET",
  "YANDEX_DISK_TOKEN",
  "VK_ACCESS_TOKEN",
  "VK_CALLBACK_SECRET",
  "VK_CONFIRMATION_STRING",
  "VK_GROUP_ID",
  "TG_ADMIN_IDS",
  "VK_ADMIN_IDS",
  "PARTICIPANT_KEY_HMAC_SECRET",
  "CF_TO_YANDEX_HMAC_SECRET",
  "YMQ_ACCESS_KEY_ID",
  "YMQ_SECRET_ACCESS_KEY",
  "YANDEX_OIDC_AUDIENCE",
  "YANDEX_SERVICE_ACCOUNT_IDS"
]

[vars]
MAX_BODY_BYTES = "32768"
TIMESTAMP_WINDOW_SECONDS = "60"
